### ISSUE TITLE
SQL initialisation question

### ISSUE THREAD

**Issue by JMurphyWeb** [SimonLab/tags-system#31]
I have a few questions...

At the moment we have:

```sql
-- Check if 'tags' table exists already; create if not
CREATE TABLE IF NOT EXISTS tags (
  id INTEGER PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  active BOOLEAN NOT NULL
);

-- Check if a tag already exists in the table; add to table if not
INSERT INTO tags (id, name, active)
  SELECT id, name, active FROM tags
  UNION --Combine the results of the above queries
  VALUES (
    000001,
    'Member Type',
    true
  )
  EXCEPT
    SELECT id, name, active FROM tags;

```

I was wondering if we want to delete all rows of the tags table at the beginning if it exists so that we are entering into a clean table?

I was also wondering why `000001` and not `1`?

Finally does the indexing start at 1 as opposed to 0 in SQL?

Overall clearly my SQL needs learning, but I was hoping to get a bit of explanation on the insert into tags query.  

As a more general/architectural question: Do we want to be adding tags in this file? or in the plugin?

**Comment by SimonLab** [comment]
I think we can at the moment clear all the data when the script is run, I'm thinking when we want to run the tests we would like the script to create a fresh database.

I think the id can be of type SERIAL, however I'm not sure if it can start at 0 we need to test that (I'm sure the value 1 is fine otherwise).

So to recap I think the idea of this script is to run it before running the tests, so the script should create a fresh and clean table and if we need some dummy content tag we can add a few in the file. You will later test the plugin function which add also some tags, so I would say both, in the file and in the plugin.

**Comment by JMurphyWeb** [comment]
Regarding id, I don't know if it will be a problem with our proposed setup, but given that the admin can change the `tags.json` file at any time, do we not want to hardcode the tag id in?

**Comment by JMurphyWeb** [comment]
Most of my questions are answered now I think this is closeable.
